services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
   ports:
  - "5001:5000" # Replace 5001 with an available port

    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm start
