version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"  # Changed the external port to 5001
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"  # Changed the external port to 3001
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: npm start
